Authentication/urls.py
from django.urls import path

app_name = 'auth'

from .views import(
	UserCreationAccountView,
	UserConnexionAccountView,
	User2FAView,
	UserForgotPassword,


	# def function logout
	# account_logout
)

urlpatterns = [
	path('signup/',UserCreationAccountView.as_view(),name='sign_up'),
	path('activate/<uidb64>/<token>/', UserCreationAccountView.activate_account, name='activate_account'),
	# path('account-create-successfuly/',UserCreationAccountView.account_create_success, name='account_create_and_sendmail_successfuly'),
	path('new_activation_link/',UserCreationAccountView.generate_new_activation_link, name='resent_new_activation_link'),
	# path('account-create-failed/',UserCreationAccountView.account_create_failed, name='account_create_and_sendmail_failed'),
	# path('account/<uidb64>/<token>/activate-success/',UserCreationAccountView.account_activate_success, name='account_activate_success'),
	# path('account/<uidb64>/<token>/activate-failed/',UserCreationAccountView.account_activate_failed, name='account_activate_failed'),
	# path('account/<uidb64>/<token>/already-activate/', UserCreationAccountView.account_already_activate, name='account_already_activate'),

	# login system
	path('signin/',UserConnexionAccountView.as_view(),name='sign_in'),
	path('account/suspended/',UserConnexionAccountView.account_suspended,name='account_suspended'),	
	path('account/not-actived/',UserConnexionAccountView.account_not_actived,name='account_suspended'),	
		
	path('account_verify/',User2FAView.as_view(),name='2fa_account_verify'),	
	path('new_account_verify_otp_code/',User2FAView.generate_new_otp_secret_code,name='new_otp_secret_code'),	

	# Forgot password
	path('account/forgot-password',UserForgotPassword.as_view(),name='forgot_password'),
	path('account/reset-password-success',UserForgotPassword.forgot_password_mail_send_success,name='reset_password_success'),
	path('account/reset-password/<uidb64>/<token>/',UserForgotPassword.reset_password,name='reset_password')

]

Eurazcom/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
# from axes.decorators import axes_dispatch

urlpatterns = [
	path('user/', include('Authentication.urls',namespace="Auth")),

	path('user/auth/', include('Usermanager.urls',namespace="Usermanager")),

    path('admin/', admin.site.urls),
    # path('admin/axes/', axes_dispatch),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Project/urls.py
from django.urls import path

app_name = 'project'

from .views import(
	CreateProject,
	CreateProjectCategory,
	CreateProjectDetails,
	ProjectBudgetAndScheduler,
	ProjectGraphicDesign,
	ProjectIngineering,
	ProjectAdvertising,
	ShowDetailsProjectByCode,

	# utilities
	ProjectUtilities,
)

urlpatterns = [
	path('u=<str:user_name>?id=<str:user_token>/project_start',CreateProject.as_view(),name='create_project_start'),
	path('u=<str:user_name>?id=<str:user_token>/?project.id=_<str:project_number>/category',CreateProjectCategory.as_view(),name='project_category'),
	path('u=<str:user_name>?id=<str:user_token>/?project.id=_<str:project_number>/details',CreateProjectDetails.as_view(),name='project_details'),
	path('u=<str:user_name>?id=<str:user_token>/?project.id=_<str:project_number>/ingineering',ProjectIngineering.as_view(),name='project_ing'),
	path('u=<str:user_name>?id=<str:user_token>/?project.id=_<str:project_number>/design_graphic',ProjectGraphicDesign.as_view(),name='required_mkt'),
	path('u=<str:user_name>?id=<str:user_token>/?project.id=_<str:project_number>/advertising',ProjectAdvertising.as_view(),name='required_ads'),
	path('u=<str:user_name>?id=<str:user_token>/?project.id=_<str:project_number>/budget_schedule',ProjectBudgetAndScheduler.as_view(),name='project_budget_schedule'),
	path('u=<str:user_name>?id=<str:user_token>/?project.id=_<str:project_number>/project_show',ShowDetailsProjectByCode.as_view(),name='project_show'),
	
	path('u=<str:user_name>?id=<str:user_token>/?project.id=_<str:project_number>/fonctionalities',ProjectFonctionalities.as_view(),name='project_fonctionalities'),
 

	# utilities
	path('project/<int:project_number>/submit_project/',ProjectUtilities.submit_project,name='project_submit'),
	path('project/<int:project_number>/delete/',ProjectUtilities.destroy_project,name='project_destroy'),
	path('project/<int:project_number>/follow/',ProjectUtilities.follow_project,name='project_follow'),
	path('project/<int:project_number>/recognize/',ProjectUtilities.recognize_project,name='project_recognize'),
	path('project/search/?q=>/',ProjectUtilities.search_project,name='project_search'),

# project_ing
# project_mkt
# project_ads
]

Authentication/models.py
from django.db import models
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import AbstractBaseUser,PermissionsMixin
from .manager import CustomUserManager


class CustomUser(AbstractBaseUser):
	name = models.CharField(max_length=150)
	email = models.EmailField(max_length=150,unique=True)
	phone = models.CharField(max_length=150,unique=True)
	country = models.CharField(max_length=50,default='CR')
	city = models.CharField(max_length=50,default='CR')
	state = models.CharField(max_length=50,default='CR')
	status = models.CharField(max_length=50,default='CR')

	activity_sector = models.CharField(max_length=150)
	avatar = models.ImageField(max_length=30,null=True,blank=True)

	is_active = models.BooleanField(default=False)
	is_suspended = models.BooleanField(default=False)
	is_closed = models.BooleanField(default=False)
	is_staff = models.BooleanField(default=False)
	is_superuser = models.BooleanField(default=False)


	USERNAME_FIELD  = 'email'

	REQUIRED_FIELDS=['name','phone']

	objects = CustomUserManager()

	# superuser = objects.create_superuser(email='superuser@example.com', name='Serge',phone='+237680638086', password='password')



	def __str__(self):
	    return self.name
    
	# def update_fields(self,**kwargs):
	# 	fields_to_update = kwargs.keys()
	# 	valid_fields = set(fields_to_update) & set(self._meta.get_fields())
	# 	if valid_fields:
	# 		for field_name in valid_fields:
	# 			setattr(self,field_name,kwargs[field_name])
	# 			self.save()

Authentication/views.py
from django.http import JsonResponse
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model,authenticate, login, logout
from django.contrib.auth.backends import ModelBackend
from django.core.exceptions import ValidationError
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import FormView,TemplateView
from django.db import OperationalError
from django.utils.http import urlsafe_base64_decode,urlsafe_base64_encode
from django.utils.encoding import force_str
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from axes.decorators import axes_dispatch
from django.contrib.auth.hashers import make_password
import pyotp, json
from datetime import datetime
from django.urls import reverse
# from django.contrib.auth.tokens import default_token_generator
 
from django.http import HttpResponse
 

from .forms import (
	ParagraphErrorList,
	CustomUserForms,
	LoginUserForms,
	User2FAForms,
	GeneratedNewLinkForm,
	ResetPasswordForm,
	UserForgotPasswordForm
)

from .helpers import ActivationAccount
from .token import account_activate_token
from .decorators import guest_only

User=get_user_model()

		
###########################################################
##################### CREATE ACCOUNT   ####################
##########################################################
@method_decorator(guest_only,name='dispatch')
class UserCreationAccountView(ActivationAccount, FormView):
	template_name = 'authentication/pages/register.html'
	page_title = 'Devenez client Eurazcom'
	mail_subject="Account Activation"
	template_mail="authentication/activation/template_activate_account.html"

	# show register page template
	def get(self,request):
		form = CustomUserForms(initial={'status':'Particular'})
		context={'form':form, 'page_title':self.page_title}
		return render(request,self.template_name,context)

	def post(self,request):
		form = CustomUserForms(request.POST,initial={'status':'Particular'}, error_class=ParagraphErrorList)
		context={'form':form, 'page_title':self.page_title}
		try:
			if form.is_valid():	            
				user = form.save(commit=False)
				user.country = 'Cameroun'
				user.city='Douala'
				user.state='LT'
				user.password=make_password(form.cleaned_data.get('password'))
				user.save()
				try:
					self.send_user_mail(request,user,user.email,self.mail_subject,self.template_mail)
				except Exception as e:
					messages.info(request,"Echec de l'envoi du mail, verifier la connexion")
				else:
					request.session['create_user_email'] = user.email
					return self.account_create_success(request)
			if not form.is_valid():
				context['errors'] = form.errors.items()
			return render(request,self.template_name,context)
		except OperationalError:
			return render(request,'exceptions/errors_access_to_database.html')
 
	# activate account logic
	@classmethod
	def activate_account(cls,request, uidb64, token):
	    try:
	        uid = force_str(urlsafe_base64_decode(uidb64))
	        user = User.objects.get(pk=uid)
	    except (TypeError, ValueError, OverflowError,User.DoesNotExist):
	        user = None
 		 
	    if user is not None and user.is_active:
    		return cls.account_already_activate(request, uidb64, token)

	    if user is not None and account_activate_token.check_token(user,token):
	    	
	    	if not user.is_active:
		        user.is_active = True
		        user.save()
		        return cls.account_activate_success(request, uidb64, token)
	    else:
	        return cls.account_activate_failed(request,uidb64,token)

	# Genrate eand send new activation link system
	@classmethod
	def generate_new_activation_link(cls,request):

		if 'create_user_email' in request.session:
			user_email = request.session['create_user_email']
			user = User.objects.get(email=user_email)
			if user is not None:
				try:
					instance = cls()
					instance.mail_subject = cls.mail_subject
					instance.template_mail = cls.template_mail
					instance.send_user_mail(request, user, user.email,instance.mail_subject,instance.template_mail)
				except Exception as e:
					messages.error(request,"Une erreur c'est produite lorsde l'envoi du mail ")
					return cls.account_create_success(request)
				else:
					messages.success(request,"Mail envoye avec succes")
					return cls.account_create_success(request)
		else:
			form = GeneratedNewLinkForm(request.POST, error_class=ParagraphErrorList)
			if request.method == 'POST':
				context = {'form':forn}
				if form.is_valid():
					form_mail = form.cleaned_data.get('email')
					user = User.objects.get(email=form_mail)
					if user is not None:
						try:
							instance.mail_subject = cls.mail_subject
							instance.template_mail = cls.template_mail
							instance.send_user_mail(request, user, user.email,instance.mail_subject,instance.template_mail)
						except Exception as e:
							messages.error(request,"Une erreur c'est produite lorsde l'envoi du mail ")
							return cls.account_create_success(request)
						else:
							messages.success(request,"Mail envoye avec succes")
							return cls.account_create_success(request)
				else:
					context['errors'] = form.errors.items()
			else:
				form = GeneratedNewLinkForm()
			return render(request,'authentication/pages/account_create_success.html',context)
		

	# Get successful account created view
	@classmethod
	def account_create_success(cls, request):
		return render(request, 'authentication/pages/account_create_success.html',{'page_title': 'Compte créé avec succès'})

	
	# Get filled account created view
	@classmethod
	def account_create_failed(cls,request):
		return render(request,'authentication/pages/account_create_failed.html',{'page_title': 'Echec de creation de compte'})

	# Get successful account activated view
	@classmethod
	def account_activate_success(cls,request, uidb64, token):
		if 'create_user_email' in request.session:
			del request.session['create_user_email']
		return render(request,'authentication/activation/activate_success.html',{'page_title': 'Activaion reussie'})

	# Get failled account activated view
	@classmethod
	def account_activate_failed(cls,request, uidb64, token):
		return render(request,'authentication/activation/activate_failed.html',{'page_title': 'Echec activaion compte'})
    
    # Get account already activated view
	@classmethod
	def account_already_activate(cls,request, uidb64, token):
		return render(request,'authentication/activation/account_already_activate.html',{'page_title':'Account already activate'})
		# return render(request,'authentication/activation/account_already_activate.html')
	

###########################################################
##################### CONNEXION SYSTEM ####################
##########################################################
@method_decorator(guest_only,name='dispatch')
class UserConnexionAccountView(ActivationAccount,FormView):
	template_name='authentication/pages/login.html'
	page_title='Connexion a votre espace client'

	def get(self,request):
		form = LoginUserForms()
		context={'form':form, 'page_title':self.page_title}
		return render(request,self.template_name,context)

	def post(self, request):
		form = LoginUserForms(request.POST,error_class=ParagraphErrorList)
		context = {'form': form, 'page_title': self.page_title}
		try:
			if form.is_valid():
				email = form.cleaned_data.get('email')
				password = form.cleaned_data.get('password')
				user = authenticate(request, email=email, password=password)
				if user is None or user.is_closed:
					messages.error(request, "Adresse email ou mot de passe est incorrecte")

				if user is not None and not user.is_active:
					messages.info(request, 'Compte non active')
					return self.account_not_actived(request)

				if user is not None and user.is_suspended:
					messages.warning(request, 'Votre compte a ete suspendu')
					return self.account_suspended(request)

				if user is not None and user.is_active:
					try:
						self.send_otp(request,user,user.email)
					except Exception as e:
						messages.error(request,"!!! Des soucis lors de l'envoi du code, reessayez plus tard")
					else:
						request.session['user_email'] = email
						return redirect('auth:2fa_account_verify')

			if not form.is_valid():
				context['errors'] = form.errors.items()

		except OperationalError:
			return render(request, 'exceptions/errors_access_to_database.html')

		return render(request, self.template_name, context)

	# Account suspended view
	@classmethod
	def account_suspended(cls,request):
		return render(request,'exceptions/account_suspended.html')

	@classmethod
	def account_not_actived(cls,request):
		return render(request,'exceptions/account_not_actived.html')


###########################################################
########################### 2FA SYSTEM ####################
##########################################################
# @method_decorator(csrf_exempt, name='dispatch')
@method_decorator(guest_only,name='dispatch')
class User2FAView(ActivationAccount, FormView):
    template_name = 'authentication/pages/2fa.html'
    page_title = 'Vérifier votre identité'

    # Vue 2FA
    def get(self, request):
        form = User2FAForms()
        context = {'form': form, 'page_title': self.page_title}
        return render(request, self.template_name, context)

    # Vérification du code
    def post(self, request):
        form = User2FAForms(request.POST, error_class=ParagraphErrorList)
        context = {'form': form, 'page_title': self.page_title}
        if form.is_valid():
        	otp = form.cleaned_data.get('otp_secret')
        	user_email = None
        	if 'user_email' in request.session:
	        	user_email = request.session['user_email']
	        else:
	        	return redirect("auth:sign_in")

Authentication/templates/authentication/activation/account_already_activate.html
{% load static %}
{% load tz %}
<!DOCTYPE html>
<html>
<head>
	<title>{{page_title}} - Eurazcom</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<section class="container">

	<div class="mb-0  p-4">
		<a href=""><img src="{% static 'img/logo.png' %}"></a>
	</div>

	<div class="col-xl-7 mx-xl-auto p-5">
		<div class="card p-3 text-center">
			<div class="text-center mb-3 p-3">
				<img src="{% static 'img/already.jpeg' %}" class="img-card img-center" width="50" height="50">
				<h6 class="fw-bold text-muted">Account Already Activate</h6>
			</div>
			<p>
				Votre compte est deja  active. <br>
				<a href="{% url 'auth:sign_in' %}" class="btn btn-primary btn-sm rounded-pill fw-bold">Connectez-vous</a>
			</p>
			 
			
		</div>
		<div class="mt-5">
			{% now "Y" as current_year %}
			&copy; copyriright Eurazcom   {{ current_year }} Tout droit reserve
		</div>
	</div>

</section>
 
</body>
</html>

Authentication/templates/authentication/activation/account_not_actived.html
{% load static %}
{% load tz %}
<!DOCTYPE html>
<html>
<head>
	<title>{{page_title}} - Eurazcom</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<section class="container">
 
	<div class="mb-0  p-4">
		<a href=""><img src="{% static 'img/logo.png' %}"></a>
	</div>

	<div class="col-xl-7 mx-xl-auto p-5">
		<div class="card p-3">
			<div class="text-center mb-3 p-3">
				<img src="{% static 'img/success.png' %}" class="img-card img-center" width="50" height="50">

				<h6 class="fw-bold text-muted">Account Information</h6>
			</div>
			<p>
				Votre compte n'est pas active
			</p>
			<p>
				 
				<!-- Button trigger modal -->
				<button type="button" class="bg-none btn btn-outline-none text-primary" style="box-shadow: none;" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
				  Demander un nouveau lien
				</button>
				<!-- <a href="">Demander un nouveau lien</a> -->
			</p>
			
		</div>
		<div class="mt-5">
			{% now "Y" as current_year %}
			&copy; Eurazcom   {{ current_year }}
		</div>
	</div>

</section>
 
</body>
</html>

Authentication/templates/authentication/activation/activate_failed.html
{% load static %}
{% load tz %}
<!DOCTYPE html>
<html>
<head>
	<title>{{page_title}} - Eurazcom</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<section class="container">
 
  <div class="mb-0  p-4">
    <a href=""><img src="{% static 'img/logo.png' %}"></a>
  </div>

	<div class="col-xl-7 mx-xl-auto p-5">
		<div class="card p-3">
			<div class="text-center mb-3 p-3">
				<img src="{% static 'img/failed.png' %}" class="img-card img-center" width="50" height="50">
				<h6 class="fw-bold text-muted">Activation Failed</h6>
			</div>
			<p>
				le processus d'ativation de votre compte n'est pas arrive a son terme. Cela peux etre du au raisons suivantes: <br>
				<ul>
					<ol>
						<li>votre lien d'activation a expire > 48h</li>
						<li></li>
					</ol>
				</ul>
			</p>
			<p>
				Si vous n'avez pas recu de lien !! 
				<!-- Button trigger modal -->
				<button type="button" class="bg-none btn btn-outline-none text-primary" style="box-shadow: none;" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
				  Demander un nouveau lien
				</button>
				<!-- <a href="">Demander un nouveau lien</a> -->
			</p>
			
		</div>
		<div class="mt-5">
			{% now "Y" as current_year %}
      &copy; Eurazcom   {{ current_year }}
		</div>
	</div>

</section>
 

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Obtenez votre nouveau lien d'activation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
	      <form novalidate>
	      	{% csrf_token %}
        	<div class="form-group mb-3">
        		<label>Enter your email adress</label>
        		{{form.email}}
        		{% autoescape off %}
        			{{ form.email.errors }}
        		{% endautoescape %}
        	</div>
        	<div class="form-group d-flex  justify-content-end">
        		<button type="submit" class="btn btn-primary btn-sm rounded-pill fw-bold" style="box-shadow: none;">Send new link</button>
        	</div>
	     </form>
      </div>
    </div>
  </div>
</div>
 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

<script>
document.querySelector('#staticBackdrop form').addEventListener('submit', function(event) {
  event.preventDefault(); // Empêche le comportement par défaut du formulaire

  var formData = new FormData(event.target);

  fetch('/u/resent_new_activation_link/', {
    method: 'POST',
    body: formData
  })
  .then(function(response) {
    if (response.ok) {
      var contentType = response.headers.get('content-type');
      if (contentType && contentType.includes('application/json')) {
        return response.json().then(function(data) {
          if (data.errors) {
            // Afficher les erreurs dans le modal
            var errors = JSON.parse(data.errors);
            for (var field in errors) {
              if (errors.hasOwnProperty(field)) {
                var errorMessages = errors[field];
                // Faites quelque chose avec les messages d'erreur, par exemple, les afficher dans le modal
                var errorContainer = document.getElementById(field + '-error');
                if (errorContainer) {
                  errorContainer.innerHTML = errorMessages.join(', ');
                }
              }
            }
          } else {
            // La requête a réussi, vous pouvez effectuer des actions supplémentaires ici
            console.log('Formulaire soumis avec succès');
            // Effectuez ici les actions que vous souhaitez après la soumission réussie du formulaire
          }
        });
      } else {
        // Gérer le cas où la réponse n'est pas au format JSON
        console.error('La réponse n\'est pas au format JSON');
      }
    } else {
      // Gérer les cas où la réponse n'est pas "ok" ici
    }
  })
  .catch(function(error) {
    // Une erreur s'est produite lors de la soumission du formulaire, vous pouvez la gérer ici
    console.error('Une erreur s\'est produite lors de la soumission du formulaire', error);
  });
});
</script>

</body>
</html>

Authentication/templates/authentication/activation/activate_success.html
{% load static %}
{% load tz %}
<!DOCTYPE html>
<html>
<head>
	<title>{{page_title}} - Eurazcom</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<section class="container">

	<div class="mb-0  p-4">
		<a href=""><img src="{% static 'img/logo.png' %}"></a>
	</div>

	<div class="col-xl-7 mx-xl-auto p-5">
		<div class="card p-3 text-center">
			<div class="text-center mb-3 p-3">
				<img src="{% static 'img/success.png' %}" class="img-card img-center" width="50" height="50">
				<h6 class="fw-bold text-muted">Account Activate Successfuly</h6>
			</div>
			<p>
				Votre compte a ete active avec success. <br>
				<a href="{% url 'auth:sign_in' %}" class="btn btn-primary btn-sm rounded-pill fw-bold">Connectez-vous</a>
			</p>
			<p>
				Si vous n'avez pas recu de lien !! 
				<!-- Button trigger modal -->
				<button type="button" class="bg-none btn btn-outline-none text-primary" style="box-shadow: none;" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
				  Demander un nouveau lien
				</button>
				<!-- <a href="">Demander un nouveau lien</a> -->
			</p>
			
		</div>
		<div class="mt-5">
			{% now "Y" as current_year %}
			&copy; Eurazcom   {{ current_year }}
		</div>
	</div>

</section>
 
</body>
</html>

Authentication/templates/authentication/activation/template_activate_account.html
{% load static %}
{% load tz %}
<!DOCTYPE html>
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style type="text/css">
    	.col-xl-7{
    		max-width: auto;
    		display: flex;
    		justify-content: center;
    		align-items: center;
    		/*border: 1px solid black;*/
    	}
    	.col-xl-7 .link{color: #fff; background: #00f; border-radius: 10px; padding: 10px; text-decoration: none; font-weight: bold; }
    </style>
</head>
<body>
	<div class="col-xl-12 mx-auto">
		<div class="card">
			<div class="card-header" style="display: flex; background: blue;color: #fff;">
				<img src="{% static 'img/logo.png' %}">
				<h2>Activation de compte client Eurazcom</h2>
			</div>
			<hr>
			<div class="card-body">
				<div class="card-text">
					Bienvenue sur Eurazcom {{user.name}}, nous sommes tres ravis de vous compte parmir notre clientelle,
					tout l'equipe sera a votre disposition de jour comme de nuit pour votre satisfaction. <br> <br>
					Afin de terminer votre inscription et acceder a votre espace client, activez votre compte en cliquand 
					sur le bouton ci-dessous.
				</div>
				<div class="card-text text-center" style="text-align: center; margin-top: 20px; margin-bottom: 20px;">
				    <a  href="{{ protocol }}://{{ domain }}{% url 'auth:activate_account' uidb64=uid token=token %}" class="link">
				    		Activer mon compte
				    </a>
				</div>
				<hr>
				<div class="card-text">
					En cas de soucis contactez notre equipe clientelle :
					<span class="text-primary">+237 699 93 96 33 - 680 63 80 86</span> 
					<span class="text-primary">Email: contact@eurazcom.com</span>
				</div>
				<hr>
				<div class="card-footer" style="background: blue; color: #fff; padding: 15px;">
					 {% now "Y" as current_year %}
					 &copy; Copyright Eurazcom   {{ current_year }} Tout droit reserve
				</div>
			</div>
		</div>
	</div>
     
</body>
</html> 
  


 